### PR TITLE
Python 3.9: random.sample() no longer permits sets

### LINKED ISSUE #10: DeprecationWarning: Sampling from a set deprecated in Python 3.9
``` 
/home/travis/virtualenv/python3.9.0/lib/python3.9/site-packages/port_for/api.py:27:
 DeprecationWarning: Sampling from a set deprecated since Python 3.9 and will be removed in a subsequent version.
    for port in random.sample(ports, min(len(ports), 100)):
```

Looks like this code will need to shift to newer methods

### PR DESCRIPTION
**Pull request by jcpunk**
Fixes #10 

https://docs.python.org/3/library/random.html#random.sample

### CODE REVIEW

**Comment by chohner** [comment]
This repo hasn't seen any work since 19 Jul 2017 :/
not sure whether this will get any attention

**Comment by kmike** [comment]
Thanks @jcpunk!

@chohner you're right, I'm not developing this repo, or monitoring issues actively. I might notice something (like this PR), but may miss things as well.

@jcpunk do you want commit permissions for this repo, or the repo being transferred somewhere?

**Comment by jcpunk** [comment]
Unfortunate, I mostly just noticed the issue coming out of a test library I'm using and figured I could give back in a clear way here.

The ClearCodeHQ folks might be interested (linked issue to PR).

**Comment by jcpunk** [comment]
For the time being, any chance for a 0.5 release with this patch to silence the notices?

**Comment by ThiefMaster** [comment]
@kmike Could you please make a release containing the fix?

**Comment by fizyk** [comment]
@kmike I'll be willing to connect the github actions and prep a release of for this package, something bit similar I'm doing for my packages, ie pytest-postgresql

**Comment by kmike** [comment]
Thanks for offering help @fizyk! I've added you as a collaborator on github. What's you pypi account name?

**Comment by fizyk** [comment]
@kmike it's fizyk: https://pypi.org/user/fizyk/

**Comment by fizyk** [comment]
Thanks @kmike. I'll create a pypi upload token for the Github Actions CI (will add it bit later though) to automate the package deployment to pypi.
I'll need to set it up in settings though, and you'll have to set it up (can push to port-for, but not manage it). Where do I send it to you?

**Comment by kmike** [comment]
Thanks @fizyk! I've added a PYPI_TOKEN secret to github, it is a pypi token with upload permissions; would it work for you? This seems easier than sending tokens around. 

> I'll need to set it up in settings though, and you'll have to set it up (can push to port-for, but not manage it). Where do I send it to you?

Ah right; I was thinking it is possible to grant you this permission, but it seems this is not the case, maybe only github orgs allow that.

**Comment by fizyk** [comment]
@kmike thanks, it'll work perfectly, and yes, just noticed this too. You either own a repo, or can be collaborator.

**Comment by fizyk** [comment]
And off we go, with 0.5.0 @kmike @jcpunk :))

**Pull request merged**
